name: pbot

on:
  repository_dispatch:
    types: [update]  # Triggered by webhook in the private repo
  push:
    branches: [main]  # Optional: for changes in the public repo
  schedule:
    - cron: "0 */5 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Initialize Git Credentials
        run: |
          git config --global user.name ${{ secrets.NAME }}
          git config --global user.email ${{ secrets.MAIL }}
          git config --global credential.helper store
          echo "https://${{ secrets.NAME }}:${{ secrets.TOKEN }}@github.com" > ~/.git-credentials

      - name: Clone Private Repo and Install Dependencies
        run: |
          git clone https://${{ secrets.TOKEN }}@github.com/Nksama/dynastypostbot pbot
          cd pbot
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Bot
        timeout-minutes: 359
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          cd pbot
          python3 main.py
