name : Tbot


on:
    schedule:
      - cron: "0 */5 * * *"
    push:
      branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9

       - name: init
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.NAME }}
           git config --global user.email ${{ secrets.MAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.NAME }}:${{ secrets.TOKEN }}@github.com" > ~/.git-credentials
       - name: cloning repo and install
         continue-on-error: true
         run: |
           git clone https://${{ secrets.NAME }}:${{ secrets.TOKEN }}@github.com/Nksama/Satorugojo Satorugojo && cd Satorugojo && pip install --upgrade pip && pip install -r requirements.txt && pip install httpcore==0.15.0
           pwd
       - name: Running
         timeout-minutes: 359
         continue-on-error: true
         run: |
           cd Satorugojo
           ls
           python3 -m gojo
